### ISSUE TITLE
Install instructions broken.

### ISSUE THREAD

**Issue by divyekapoor** [zweifisch/google-search-cli#1]
google-search-cli version 0.5 doesn't install with:

$ pip install google-search-cli

Downloading/unpacking google-search-cli

  Getting page http://pypi.python.org/simple/google-search-cli/
  URLs to search for versions for google-search-cli:
- http://pypi.python.org/simple/google-search-cli/
  Analyzing links from page https://pypi.python.org/simple/google-search-cli/
    Found link https://pypi.python.org/packages/source/g/google-search-cli/google-search-cli-0.0.1.tar.gz#md5=ce6f176683e39584ca7f4ac2ea9f80b0 (from https://pypi.python.org/simple/google-search-cli/), version: 0.0.1
    Found link https://pypi.python.org/packages/source/g/google-search-cli/google-search-cli-0.0.2.tar.gz#md5=b55833057d7e1909bc5316bd40702a76 (from https://pypi.python.org/simple/google-search-cli/), version: 0.0.2
    Found link https://pypi.python.org/packages/source/g/google-search-cli/google-search-cli-0.0.3.tar.gz#md5=842fa793fc75b6450e141de9ea2af844 (from https://pypi.python.org/simple/google-search-cli/), version: 0.0.3
    Found link https://pypi.python.org/packages/source/g/google-search-cli/google-search-cli-0.0.5.tar.gz#md5=e6943f6d570ae86bb9c5081f10c7072e (from https://pypi.python.org/simple/google-search-cli/), version: 0.0.5
  Using version 0.0.5 (newest of versions: 0.0.5, 0.0.3, 0.0.2, 0.0.1)
  Error <urlopen error [Errno 1] _ssl.c:507: error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm> while getting https://pypi.python.org/packages/source/g/google-search-cli/google-search-cli-0.0.5.tar.gz#md5=e6943f6d570ae86bb9c5081f10c7072e (from https://pypi.python.org/simple/google-search-cli/)

Cleaning up...

  Removing temporary dir /private/var/folders/00/14w4r000h01000cxqpysvccm004lhl/T/pip_build_divye...
Exception:
Traceback (most recent call last):
  File "/Users/divye/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/Users/divye/anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/divye/anaconda/lib/python2.7/site-packages/pip/req.py", line 1092, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/Users/divye/anaconda/lib/python2.7/site-packages/pip/req.py", line 1238, in unpack_url
    retval = unpack_http_url(link, location, self.download_cache, self.download_dir)
  File "/Users/divye/anaconda/lib/python2.7/site-packages/pip/download.py", line 602, in unpack_http_url
    resp = _get_response_from_url(target_url, link)
  File "/Users/divye/anaconda/lib/python2.7/site-packages/pip/download.py", line 638, in _get_response_from_url
    resp = urlopen(target_url)
  File "/Users/divye/anaconda/lib/python2.7/site-packages/pip/download.py", line 176, in __call__
    response = self.get_opener(scheme=scheme).open(url)
  File "/Users/divye/anaconda/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/Users/divye/anaconda/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/Users/divye/anaconda/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/Users/divye/anaconda/lib/python2.7/site-packages/pip/download.py", line 155, in https_open
    return self.do_open(self.specialized_conn_class, req)
  File "/Users/divye/anaconda/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:507: error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm>

$ pip --version
pip 1.4.1 from /Users/divye/anaconda/lib/python2.7/site-packages (python 2.7)

**Comment by zweifisch** [comment]
Hi, this looks like a pip issue, or a network problem.

**Comment by divyekapoor** [comment]
It failed a couple of times in a row when I filed the issue... Seems to not be an issue now..
Closing out the issue. 

Thanks for responding...
